config/routes.rb
Rails.application.routes.draw do
  resources :products
  root to: 'home#index'
  get 'home/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :stores, controllers: {
      sessions: 'store/sessions',
      registrations: 'store/registrations'
  }

  match "*a", controller: :home, action: :index, via: [:get]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include Mongoid::Document
  include CanCan::Ability

  def initialize(store)
    if store
      can :manage, :rails_admin
      can :read, :dashboard

      can :manage, Product, store_id: store.id
      can [:read, :update], Store, _id: store.id
    end
  end
end

app/models/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    index_name "#{self.to_s.downcase}-#{Rails.env}"

    def self.search(query)
      __elasticsearch__.search(query, size: 1000)
    end

    def as_indexed_json(**args)
      as_json(except: [:id, :_id])
    end
  end
end

app/models/product.rb
class Product
  include Mongoid::Document
  include Searchable

  validates_presence_of :name, :price, :url, :store

  field :name, type: String
  field :price, type: Float
  field :installment, type: Hash
  field :url, type: String
  belongs_to :store

  mount_uploader :image, ImageUploader, mount_on: :image
end

app/models/store.rb
class Store
  include Mongoid::Document
  include Searchable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :image, presence: true

  before_update do
    unless valid?
      if errors.messages[:password_confirmation].present? || errors.messages[:password].present?
        self.password_confirmation = nil
        self.password = nil
      end
    end
  end

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  has_many :products, dependent: :destroy
  field :name, type: String
  field :site, type: String

  mount_uploader :image, ImageUploader, mount_on: :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource
  before_action :authenticate_store!

  private

  def layout_by_resource
    if devise_controller?
      "unauthenticated"
    else
      "application"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
  layout 'marketplace'
  before_action :get_stores, only: [:index]
  before_action :get_products, only: [:index]

  def index
  end

  private

  def get_products
    @products = Product.search("*#{params[:query]}*").records.records

    if params[:min_price].present?
      @products = @products.where(:price.gte => params[:min_price])
    end
    if params[:max_price].present?
      @products = @products.where(:price.lte => params[:max_price])
    end
    if params[:stores].present?
      @products = @products.in(store: params[:stores])
    end

    @quantity = @products.count
  end

  def get_stores
    @stores = Store.search("*").records.records
  end
end

app/controllers/store/confirmations_controller.rb
# frozen_string_literal: true

class Store::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/store/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Store::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/store/passwords_controller.rb
# frozen_string_literal: true

class Store::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/store/registrations_controller.rb
# frozen_string_literal: true

class Store::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :name,
      :site,
      :image,
      :email,
      :password,
      :password_confirmation
    ])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/store/sessions_controller.rb
# frozen_string_literal: true

class Store::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/store/unlocks_controller.rb
# frozen_string_literal: true

class Store::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_filters.html.erb
<% mobile ||= false %>
<div class="<%= mobile ? 'p-15' : '' %>">
  <div class="current-page">Produtos (<%= @quantity %> encontrados)</div>
  <%= "<hr>".html_safe if mobile %>
  <div class="<%= mobile ? '' : 'card' %>">
    <% unless mobile %>
      <div class="card-header grey lighten-2">Filtros</div>
    <% end %>
    <div class="filters">
      <div class="filter-group">
        <span class="filter-title">Preço</span>
        <div class="text-range-group">
          <div class="input-field">
            <div class="prefix">R$</div>
            <%= form.text_field :min_price, value: params[:min_price] %>
          </div>
          <div class="text-separator">até</div>
          <div class="input-field">
            <div class="prefix">R$</div>
            <%= form.text_field :max_price, value: params[:max_price] %>
          </div>
        </div>
      </div>

      <div class="filter-group">
        <span class="filter-title">Lojas</span>
        <% @stores.map do |store| %>
          <p class="stores-flags">
            <label>
              <% store_is_checked = params[:stores].nil? || params[:stores]&.include?(store._id.to_s) rescue false %>
              <%= form.check_box :stores, {multiple: true, class: 'filled-in', checked: store_is_checked}, store._id %>
              <span><%= store.name %></span>
            </label>
          </p>
        <% end %>
      </div>

      <div class="center">
        <%= form.submit 'Pesquisar', class: 'waves-effect waves-light btn' %>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= form_with(url: home_index_path, method: :get, local: true, class: 'col s12') do |form| %>

  <div id="filters-slide-out" class="sidenav">
    <%= render 'filters', form: form, params: params, mobile: true %>
  </div>

  <div class="row">
    <div class="col s12 l3 hide-on-med-and-down">
      <%= render 'filters', form: form, params: params %>
    </div>
    <div class="col s12 l9">
      <div class="row">
        <div class="col s12">
          <div class="flexbox" style="padding-right: 17px">
            <a href="javascript:void(0)" data-target="filters-slide-out"
               class="pr- hide-on-large-only sidenav-trigger black-text" style="padding: 10px 20px 10px 17px">
              <i class="material-icons">menu</i>
            </a>

            <%= form.text_field :query, value: params[:query], class: 'search-field', placeholder: "Pesquisar produtos" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col s12">
          <% if @quantity > 0 %>
            <div class="row">
              <% @products.each do |product| %>
                <div class="col m4">
                  <div class="card large hoverable product">
                    <div class="card-image" style="max-height: 53%;">
                      <img src="<%= product.image %>">
                    </div>
                    <div class="card-content">
                      <p class="product-name"><%= product.name %></p>
                      <p class="product-price">
                        <span><%= number_to_currency(product.price, unit: "R$") %></span>
                        <% if product.installment.present? %>
                          <span class="grey-text">ou</span>
                          <span>
                            <% number_of_installments = product.installment["NumberOfInstallments"] %>
                            <% value_of_installments = product.price.to_f / number_of_installments %>
                            <%= number_of_installments %> x <%= number_to_currency(value_of_installments, unit: "R$") %>
                          </span>
                        <% end %>
                      </p>
                    </div>
                    <% if product.url.present? %>
                      <div class="card-action center-align">
                        <%= link_to product.url, class: 'waves-effect waves-light btn', target: '_blank' do %>
                          Ver na loja
                          <i class="material-icons right">open_in_new</i>
                      <% end %>
                      </div>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
          <% else %>
            <div class="not_found center">
              <%= image_tag('not_found.svg', size: "250x250") %>
              <h5>Não foi encontrado nenhum produto!</h5>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketplaceChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
      <% if current_store %>
        <%= link_to 'Logout', destroy_store_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Login', new_store_session_path %>
      <% end %>

      <div>
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/layouts/marketplace.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Marketplace</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

  <%= stylesheet_link_tag 'marketplace', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'marketplace', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <%= render partial: 'layouts/shared/navbar' %>

  <div style="display: none">
    <p class="flash-messages notice"><%= notice %></p>
    <p class="flash-messages alert"><%= alert %></p>
  </div>
<!--  <div class="col s12">-->
<!--    <a href="#!" class="breadcrumb teal-text text-darken-2">First</a>-->
<!--    <a href="#!" class="breadcrumb teal-text text-darken-2">Second</a>-->
<!--    <a href="#!" class="breadcrumb grey-text text-darken-4">Third</a>-->
<!--  </div>-->
  <main class="white">
    <%= yield %>
  </main>
</body>
</html>

app/views/layouts/shared/_navbar.html.erb
<ul id="dropdown" class="dropdown-content" style="top: 50px;">
  <% if current_store %>
    <li><%= link_to 'Ir para Painel', rails_admin_path %></li>
    <li><%= link_to 'Logout', destroy_store_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to 'Login', new_store_session_path %></li>
    <li><%= link_to "Fazer Cadastro", new_registration_path(:store) %></li>
  <% end %>
</ul>

<nav class="nav-extended teal">
  <div class="nav-wrapper">
    <a href="#" class="brand-logo left">
      Marketplace
    </a>
    <ul class="right">
      <li>
        <a href="javascript:void(0)" class="dropdown-trigger" data-target="dropdown">
          Perfil
          <i class="material-icons right">arrow_drop_down</i>
        </a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/unauthenticated.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Marketplace</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

  <%= stylesheet_link_tag 'unauthenticated', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'unauthenticated', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <%= render partial: 'layouts/shared/navbar' %>

  <div style="display: none">
    <p class="flash-messages notice"><%= notice %></p>
    <p class="flash-messages alert"><%= alert %></p>
  </div>

  <%# if current_store %>
    <%#= link_to 'Logout', destroy_store_session_path, method: :delete %>
  <%# else %>
    <%#= link_to 'Login', new_store_session_path %>
  <%# end %>
<!--  <div class="col s12">-->
<!--    <a href="#!" class="breadcrumb teal-text text-darken-2">First</a>-->
<!--    <a href="#!" class="breadcrumb teal-text text-darken-2">Second</a>-->
<!--    <a href="#!" class="breadcrumb grey-text text-darken-4">Third</a>-->
<!--  </div>-->
  <main class="white">
    <%= yield %>
  </main>
</body>
</html>